### ISSUE TITLE
[Discussion] Scalability

### ISSUE THREAD

**Issue by kennedyoliveira** [BranislavLazic/akka-cqrs-activator#3]
Hello!

Thank you for making this source code available, it's very useful, i'm studying akka and searching for patterns, best practices and ways of doing things, and i have a doubt based on this implementation.

How it's supposed to scale? Since it creates a new Actor for each issue, if a have billions of issues, how can i scale it?

**Comment by BranislavLazic** [comment]
Hi. 
In such scenario, I would probably introduce Akka cluster sharding for the IssueRepository actor and add more Cassandra instances in its cluster. In such case, I would have an even distribution of load over the cluster of application instances (sharding region). You can take a look at [Reactive Flows](https://github.com/hseeberger/reactive-flows). As far as I remember, that example covers scaling too while my example is mostly focused on ES and CQRS.

**Comment by kennedyoliveira** [comment]
Hello @BranislavLazic,
thanks for the answers, i'll check the link you pointed, looks like a great example too!
I'll check akka cluster sharding, i still didn't used this one.
I have a question, maybe learning the cluster sharding would answer it, but i'll ask anyway, using sharding, the IssueRepositoryManager would still be needed?

**Comment by BranislavLazic** [comment]
Yes. To forward messages toward issue repository sharding region.

**Comment by kennedyoliveira** [comment]
Thank you!
